title: alexeyfv
description: Articles about .NET, C# and much more
baseurl: ""
url: "http://www.alexeyfv.xyz/"

theme: minima
plugins:
  - jekyll-feed

author:
  name: Â© 2024 Alexey Fedorov
  
minima:
  skin: dark
  social_links:
    github: alexeyfv
    linkedin: alexeyfv
    telegram: alexeyfv  

header_pages:
  - _pages/tags.html
  - _pages/projects.md
  - _pages/about.md

include: ['_pages']

show_excerpts: true